### ISSUE TITLE
【suggestion】some basic SSE intrinsic function can not find in this project

### ISSUE THREAD

**Issue by liuzhuni** [kunpengcompute/AvxToNeon#2]
some basic SSE intrinsic function can not find in this project, such as the  _mm_store_ps、_mm_store_si128 functions. May be you can combine https://github.com/DLTcollab/sse2neon/blob/master/sse2neon.h

**Comment by ccxiaop** [comment]
we developed these interfaces first according to the frequency of use, and will develop or combine  other sse and avx interfaces in the future.thanks.
